### PR TITLE
Develop 84 plotting script

### PR DESCRIPTION
**Pull request by mattldawson**
================================================

Tag name:

Originator(s):

Date:

Issue(s) resolved: #84 

One-line Summary:

Purpose of changes:

Files added:

Files deleted:

Files modified:

Regression test status:

### CODE REVIEW

**Comment by AndrewJConley** [comment]
This is great!  If "python3 plot.py O3 CO2"  produced O3.png and CO2.png in a "plots" directory when we executed "python3 plot.py O3 CO2" we would be very close to having a web service showing the plots.  What do you think?

**Comment by mattldawson** [comment]
yeah - maybe we're closer than we think! could be worth thinking about setting up?

**Comment by carl-drews** [comment]
FYI or you may already know this:

Django provides a way for Python to pass a plot back to the browser in
memory, rather than having to create a (temporary) disk file.

Carl

**Comment by AndrewJConley** [comment]
@carl-drews This will run inside the docker container.  I plan to use a stripped-down server to provide the user with a way to look at the data.  So Django is a bit of overkill, as long as the python can deliver the result through script.  See  https://github.com/AndrewJConley/Simple_png_display_server as a rough idea of what type of server I'm using.  Perhaps you might want to flesh out the display of the reactions?

**Comment by AndrewJConley** [comment]
@carl-drews I wonder if flask might be a better solution for us. https://towardsdatascience.com/python-plotting-api-expose-your-scientific-python-plots-through-a-flask-api-31ec7555c4a8

**Pull request merged**
